"""Add rating to hotel and restaurant

Revision ID: 127137dbe41f
Revises: 3f62fa4405b1
Create Date: 2026-08-13 23:34:35.402208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127137dbe41f'
down_revision = '3f62fa4405b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_claim_requests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_requests'))
    )
    op.create_table('food_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_food_categories_restaurant_id_restaurants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_categories'))
    )
    op.create_table('food_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_veg', sa.Boolean(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['food_categories.id'], name=op.f('fk_food_items_category_id_food_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_items'))
    )
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reviews_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reviews_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('temple_gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_video', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('temples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reviews_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temples', schema=None) as batch_op:
        batch_op.drop_column('reviews_count')
        batch_op.drop_column('rating')

    with op.batch_alter_table('temple_gallery', schema=None) as batch_op:
        batch_op.drop_column('video_url')
        batch_op.drop_column('is_video')

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('reviews_count')
        batch_op.drop_column('rating')

    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_column('reviews_count')
        batch_op.drop_column('rating')

    op.drop_table('food_items')
    op.drop_table('food_categories')
    op.drop_table('claim_requests')
    # ### end Alembic commands ###
