"""Add new fields to Temple

Revision ID: 73f0299c0fe9
Revises: d5f0c78041ad
Create Date: 2026-08-13 22:01:58.098977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f0299c0fe9'
down_revision = 'd5f0c78041ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('official_website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('expected_duration', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('best_time_to_visit', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('important_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temples', schema=None) as batch_op:
        batch_op.drop_column('important_notes')
        batch_op.drop_column('best_time_to_visit')
        batch_op.drop_column('expected_duration')
        batch_op.drop_column('official_website')

    # ### end Alembic commands ###
