"""Phase 2 SEO and Collector models

Revision ID: b3b0beda2f1d
Revises: 127137dbe41f
Create Date: 2026-08-15 19:49:45.227608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b0beda2f1d'
down_revision = '127137dbe41f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()

    if 'collector_logs' not in tables:
        op.create_table('collector_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('start_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('end_time', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('sources_processed', sa.Integer(), nullable=True),
        sa.Column('discoveries', sa.Integer(), nullable=True),
        sa.Column('errors', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_collector_logs'))
        )

    if 'discovered_entities' not in tables:
        op.create_table('discovered_entities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_url', sa.String(length=500), nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('extracted_data', sa.JSON(), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_discovered_entities'))
        )

    temple_columns = [c['name'] for c in inspector.get_columns('temples')]

    with op.batch_alter_table('temples', schema=None) as batch_op:
        if 'slug' not in temple_columns:
            batch_op.add_column(sa.Column('slug', sa.String(length=200), nullable=True))
        if 'seo_title' not in temple_columns:
            batch_op.add_column(sa.Column('seo_title', sa.String(length=200), nullable=True))
        if 'seo_description' not in temple_columns:
            batch_op.add_column(sa.Column('seo_description', sa.Text(), nullable=True))
        if 'canonical_url' not in temple_columns:
            batch_op.add_column(sa.Column('canonical_url', sa.String(length=255), nullable=True))
        if 'history' not in temple_columns:
            batch_op.add_column(sa.Column('history', sa.Text(), nullable=True))
        if 'significance' not in temple_columns:
            batch_op.add_column(sa.Column('significance', sa.Text(), nullable=True))
        if 'how_to_reach' not in temple_columns:
            batch_op.add_column(sa.Column('how_to_reach', sa.Text(), nullable=True))
        if 'faqs' not in temple_columns:
            batch_op.add_column(sa.Column('faqs', sa.JSON(), nullable=True))
        if 'is_featured' not in temple_columns:
            batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))

    op.execute("UPDATE temples SET slug = LOWER(REPLACE(name, ' ', '-')) WHERE slug IS NULL")

    temple_indexes = [ix['name'] for ix in inspector.get_indexes('temples')]

    duplicates = conn.execute(sa.text("SELECT slug, COUNT(*) FROM temples WHERE slug IS NOT NULL GROUP BY slug HAVING COUNT(*) > 1")).fetchall()
    if duplicates:
        raise Exception(f"Migration blocked: Found duplicate generated slugs in the temples table: {duplicates}. Please resolve these duplicates manually to avoid data corruption.")

    with op.batch_alter_table('temples', schema=None) as batch_op:
        if batch_op.f('ix_temples_slug') not in temple_indexes:
            batch_op.create_index(batch_op.f('ix_temples_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temples_slug'))
        batch_op.drop_column('is_featured')
        batch_op.drop_column('faqs')
        batch_op.drop_column('how_to_reach')
        batch_op.drop_column('significance')
        batch_op.drop_column('history')
        batch_op.drop_column('canonical_url')
        batch_op.drop_column('seo_description')
        batch_op.drop_column('seo_title')
        batch_op.drop_column('slug')

    op.drop_table('discovered_entities')
    op.drop_table('collector_logs')
    # ### end Alembic commands ###
