"""add temple gallery table

Revision ID: c1e0b02d9955
Revises: f8ba6aa77a58
Create Date: 2026-08-03 13:22:50.703482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e0b02d9955'
down_revision = 'f8ba6aa77a58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temple_gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temple_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temple_gallery')
    # ### end Alembic commands ###
