"""Add Auth and Trust models with batch enabled

Revision ID: efab642e6b4e
Revises: 2438afda0d53
Create Date: 2026-08-13 22:25:25.495897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efab642e6b4e'
down_revision = '2438afda0d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_categories_name'), ['name'])
        batch_op.create_unique_constraint(batch_op.f('uq_categories_slug'), ['slug'])

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_drivers_phone'), ['phone'])
        batch_op.create_unique_constraint(batch_op.f('uq_drivers_vehicle_number'), ['vehicle_number'])
        batch_op.create_foreign_key(batch_op.f('fk_drivers_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_hotels_slug'), ['slug'])
        batch_op.create_foreign_key(batch_op.f('fk_hotels_owner_id_users'), 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_places_slug'), ['slug'])

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_restaurants_slug'), ['slug'])
        batch_op.create_foreign_key(batch_op.f('fk_restaurants_owner_id_users'), 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_restaurants_owner_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_restaurants_slug'), type_='unique')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_places_slug'), type_='unique')

    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_hotels_owner_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_hotels_slug'), type_='unique')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_drivers_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_drivers_vehicle_number'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_drivers_phone'), type_='unique')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_categories_slug'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_categories_name'), type_='unique')

    # ### end Alembic commands ###
