"""add darshan timing fields

Revision ID: f8ba6aa77a58
Revises: eb81c5d03169
Create Date: 2026-08-03 12:23:43.979012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ba6aa77a58'
down_revision = 'eb81c5d03169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('morning_open', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('morning_close', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('evening_open', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('evening_close', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temples', schema=None) as batch_op:
        batch_op.drop_column('evening_close')
        batch_op.drop_column('evening_open')
        batch_op.drop_column('morning_close')
        batch_op.drop_column('morning_open')

    # ### end Alembic commands ###
